# Generated by Django 4.2.11 on 2024-04-08 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
